version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ecometer
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
